version: '2.3'
services:
  app:
    container_name: ${CONTAINER_APP_NAME}
    runtime: ${runtime}
    build:
      dockerfile: $DOCKER_FILE
      context: .
      network: host
    networks:
      - default
      - web
    ports:
      - $EXPOSED_PORTS
    environment:
      - VIRTUAL_HOST=${DOMAIN}
      - VIRTUAL_PROTO=https
    restart: unless-stopped
    volumes:
      - ./app/data:/code/app/data
      - ./logs:/code/logs
networks:
  web:
    external:
      name: ${EXTERNAL_NETWORK}
